import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2, XCircle } from "lucide-react";
import toast from "react-hot-toast";
import api from "../../services/api";

type QuestionResult = { questionId: string; order?: number; sectionTitle?: string; questionType: string; questionText: string; maxMarks: number; marksObtained: number; isCorrect: boolean | null; chosenOptions: Array<{ id: string; text?: string }>; correctOptions: Array<{ id: string; text?: string }>; studentCode?: string | null; studentText?: string | null; starterCode?: string | null; solutionCode?: string | null; expectedOutput?: string | null; feedback?: string | null };
type Marksheet = { student: { name: string; enrollmentNo: string; batch: string; division: string }; test: { title: string; subject: string; totalMarks: number }; status: string; mcqScore: number; codeScore: number; totalScore: number; percentage: number; evaluationStatus: string; sectionTotals: Array<{ section: string; earned: number; max: number }>; questions: QuestionResult[] };

export default function DetailedMarksheet() {
  const { studentTestId = "" } = useParams();
  const [result, setResult] = useState<Marksheet | null>(null);
  useEffect(() => { api.get(`/grading/student/result/${studentTestId}`).then((response) => setResult(response.data.data)).catch((error) => toast.error(error.response?.data?.message || "This result is not available")); }, [studentTestId]);
  if (!result) return <div className="min-h-screen bg-slate-950 p-8 text-slate-300">Loading marksheet…</div>;
  const passed = result.percentage >= 40 && !["TERMINATED", "VIOLATION_SUBMITTED"].includes(result.status);
  return <div className="min-h-screen bg-slate-950 p-6 text-white lg:p-10"><div className="mx-auto max-w-5xl"><Link to="/student/results" className="inline-flex items-center gap-2 text-sm text-blue-300"><ArrowLeft size={16}/>All results</Link><header className="mb-6 mt-5 rounded-2xl border border-slate-700 bg-slate-900 p-6"><p className="text-sm text-blue-300">{result.test.subject} · {result.student.name} · {result.student.enrollmentNo}</p><h1 className="mt-1 text-2xl font-bold">{result.test.title} — Marksheet</h1><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["MCQ score", result.mcqScore], ["Code score", result.codeScore], ["Total score", `${result.totalScore} / ${result.test.totalMarks}`], ["Percentage", `${Number(result.percentage).toFixed(1)}%`]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-800 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</div><div className={`mt-4 inline-flex rounded-full px-3 py-1 text-xs font-bold ${passed ? "bg-emerald-500/15 text-emerald-200" : "bg-red-500/15 text-red-200"}`}>{passed ? "PASS" : "FAIL"}</div></header>
    <section className="mb-6 rounded-xl border border-slate-700 bg-slate-900 p-5"><h2 className="mb-4 font-semibold">Section breakdown</h2><div className="grid gap-3 sm:grid-cols-2">{result.sectionTotals.map((section) => <div key={section.section} className="flex justify-between rounded-lg bg-slate-800 p-3 text-sm"><span>{section.section}</span><span className="font-semibold">{section.earned} / {section.max}</span></div>)}</div></section>
    <h2 className="mb-4 text-xl font-bold">Question review</h2><div className="space-y-4">{result.questions.map((question, index) => <article key={question.questionId} className="rounded-xl border border-slate-700 bg-slate-900 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs uppercase text-slate-400">Question {question.order ?? index + 1} · {question.sectionTitle || "General"} · {question.questionType.replaceAll("_", " ")}</p><span className="inline-flex items-center gap-1 text-sm font-semibold">{question.marksObtained} / {question.maxMarks}{question.isCorrect === null ? null : question.isCorrect ? <CheckCircle2 className="text-emerald-400" size={16}/> : <XCircle className="text-red-400" size={16}/>}</span></div><p className="mt-3 whitespace-pre-wrap font-medium">{question.questionText}</p>{question.chosenOptions.length > 0 || question.correctOptions.length > 0 ? <div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Your answer</p><p className="mt-1 text-sm">{question.chosenOptions.map((option) => option.text).join(", ") || "Not answered"}</p></div><div><p className="text-xs text-slate-500">Correct answer</p><p className="mt-1 text-sm text-emerald-200">{question.correctOptions.map((option) => option.text).join(", ")}</p></div></div> : <><div className="mt-4"><p className="mb-1 text-xs text-slate-500">Your submitted answer</p><pre className="max-h-72 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-950 p-3 text-sm">{question.studentCode || question.studentText || "No answer submitted"}</pre></div>{question.feedback && <div className="mt-3 rounded-lg border border-blue-500/20 bg-blue-500/5 p-3 text-sm"><span className="font-semibold text-blue-200">Faculty feedback: </span>{question.feedback}</div>}</>}</article>)}</div></div></div>;
}
