import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, AlertTriangle, BarChart3, GraduationCap, TrendingUp, Users } from "lucide-react";
import toast from "react-hot-toast";
import api from "../../services/api";

type Analytics = { totalEnrolled: number; totalAppeared: number; totalSubmitted: number; totalTerminated: number; highestScore: number; lowestScore: number; averageScore: number; medianScore: number; passCount: number; failCount: number; passRate: number; totalViolations: number; scoreDistribution: Array<{ label: string; count: number }>; batchDivisionAverages: Array<{ group: string; attempts: number; average: number }>; violationsByType: Array<{ type: string; count: number }> };
const format = (value: number) => `${Number(value || 0).toFixed(1)}%`;

export default function TestAnalytics() {
  const { testId = "" } = useParams();
  const [data, setData] = useState<Analytics | null>(null);
  useEffect(() => { api.get(`/grading/test/${testId}/analytics`).then((response) => setData(response.data.data)).catch((error) => toast.error(error.response?.data?.message || "Could not load analytics")); }, [testId]);
  if (!data) return <div className="p-8 text-slate-300">Loading analytics…</div>;
  const highestBucket = Math.max(1, ...data.scoreDistribution.map((item) => item.count));
  const maxViolation = Math.max(1, ...data.violationsByType.map((item) => item.count));
  const cards = [{ label: "Class average", value: format(data.averageScore), icon: TrendingUp, color: "text-blue-300" }, { label: "Pass rate", value: format(data.passRate), icon: GraduationCap, color: "text-emerald-300" }, { label: "Highest score", value: format(data.highestScore), icon: BarChart3, color: "text-violet-300" }, { label: "Total violations", value: data.totalViolations, icon: AlertTriangle, color: "text-amber-300" }];
  return <div className="p-6 text-white lg:p-8"><Link to={`/faculty/grading/test/${testId}/submissions`} className="mb-5 inline-flex items-center gap-2 text-sm text-blue-300"><ArrowLeft size={16}/>Submissions</Link><div className="mb-7"><p className="text-sm uppercase tracking-widest text-blue-400">Class performance</p><h1 className="mt-1 text-3xl font-bold">Test analytics</h1><p className="mt-1 text-sm text-slate-400">{data.totalEnrolled} enrolled · {data.totalAppeared} appeared · {data.totalSubmitted} submitted · {data.totalTerminated} terminated</p></div>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-xl border border-slate-700 bg-slate-800 p-4"><div className="flex items-center justify-between"><p className="text-sm text-slate-400">{label}</p><Icon className={color} size={18}/></div><p className={`mt-2 text-3xl font-bold ${color}`}>{value}</p></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 className="mb-5 font-semibold">Score distribution</h2><div className="flex h-56 items-end justify-around gap-3 border-b border-slate-600 px-2">{data.scoreDistribution.map((bucket) => <div key={bucket.label} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-sm text-slate-300">{bucket.count}</span><div title={`${bucket.count} students`} className="w-full max-w-20 rounded-t-md bg-blue-500 transition-all" style={{ height: `${Math.max(bucket.count ? 6 : 0, bucket.count / highestBucket * 78)}%` }}/><span className="pb-2 text-center text-[11px] text-slate-400">{bucket.label}</span></div>)}</div><div className="mt-4 flex justify-between text-sm text-slate-400"><span>Median {format(data.medianScore)}</span><span>Pass {data.passCount} · Fail {data.failCount}</span></div></section>
      <section className="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 className="mb-4 font-semibold">Violation frequency</h2>{data.violationsByType.length === 0 ? <p className="text-sm text-slate-400">No violations recorded.</p> : <div className="space-y-3">{data.violationsByType.map((item) => <div key={item.type}><div className="mb-1 flex justify-between text-xs"><span>{item.type.replaceAll("_", " ")}</span><span className="text-slate-400">{item.count}</span></div><div className="h-2 overflow-hidden rounded bg-slate-700"><div className="h-full rounded bg-rose-500" style={{ width: `${item.count / maxViolation * 100}%` }}/></div></div>)}</div>}</section>
      <section className="rounded-xl border border-slate-700 bg-slate-800 p-5 xl:col-span-2"><h2 className="mb-4 flex items-center gap-2 font-semibold"><Users size={18}/>Batch / division averages</h2>{data.batchDivisionAverages.length === 0 ? <p className="text-sm text-slate-400">No submitted attempts yet.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="py-2">Batch / Division</th><th className="py-2">Attempts</th><th className="py-2">Average</th><th className="py-2">Comparison</th></tr></thead><tbody className="divide-y divide-slate-700">{data.batchDivisionAverages.map((item) => <tr key={item.group}><td className="py-3">{item.group}</td><td className="py-3">{item.attempts}</td><td className="py-3 font-semibold">{format(item.average)}</td><td className="w-1/2 py-3"><div className="h-2 rounded bg-slate-700"><div className="h-full rounded bg-indigo-400" style={{ width: `${Math.min(100, Math.max(0, item.average))}%` }}/></div></td></tr>)}</tbody></table></div>}</section></div>
  </div>;
}
